eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        
logging:
  level:
    org.springframework: INFO


management:
  endpoints:
    web:
      exposure:
        include: health,info
